//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoCarlos.NET.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoCarlos.NET.Resources.SettingsWindow", typeof(SettingsWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviation.
        /// </summary>
        public static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on MM score.
        /// </summary>
        public static string BasedOnMM {
            get {
                return ResourceManager.GetString("BasedOnMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom group bar.
        /// </summary>
        public static string BottomGroupBar {
            get {
                return ResourceManager.GetString("BottomGroupBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        public static string Criteria {
            get {
                return ResourceManager.GetString("Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria type.
        /// </summary>
        public static string CriteriaTooltip {
            get {
                return ResourceManager.GetString("CriteriaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria 1.
        /// </summary>
        public static string Criterium1 {
            get {
                return ResourceManager.GetString("Criterium1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria 2.
        /// </summary>
        public static string Criterium2 {
            get {
                return ResourceManager.GetString("Criterium2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria 3.
        /// </summary>
        public static string Criterium3 {
            get {
                return ResourceManager.GetString("Criterium3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria 4.
        /// </summary>
        public static string Criterium4 {
            get {
                return ResourceManager.GetString("Criterium4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string GRD {
            get {
                return ResourceManager.GetString("GRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade from 9d to 30k.
        /// </summary>
        public static string GRDW {
            get {
                return ResourceManager.GetString("GRDW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handicap.
        /// </summary>
        public static string Handicap {
            get {
                return ResourceManager.GetString("Handicap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handicap ceiling.
        /// </summary>
        public static string HandicapCeiling {
            get {
                return ResourceManager.GetString("HandicapCeiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handicap reduced by.
        /// </summary>
        public static string HandicapReduction {
            get {
                return ResourceManager.GetString("HandicapReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to McMahon score.
        /// </summary>
        public static string MMS {
            get {
                return ResourceManager.GetString("MMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MMSD {
            get {
                return ResourceManager.GetString("MMSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of wins.
        /// </summary>
        public static string NBW {
            get {
                return ResourceManager.GetString("NBW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NBWD {
            get {
                return ResourceManager.GetString("NBWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null.
        /// </summary>
        public static string NUL {
            get {
                return ResourceManager.GetString("NUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter set.
        /// </summary>
        public static string NULD {
            get {
                return ResourceManager.GetString("NULD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of rounds.
        /// </summary>
        public static string NumberOfRounds {
            get {
                return ResourceManager.GetString("NumberOfRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string RAT {
            get {
                return ResourceManager.GetString("RAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating from 2950 to -900.
        /// </summary>
        public static string RATD {
            get {
                return ResourceManager.GetString("RATD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SODOS.
        /// </summary>
        public static string SDS {
            get {
                return ResourceManager.GetString("SDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of defeated opponents scores.
        /// </summary>
        public static string SDSW {
            get {
                return ResourceManager.GetString("SDSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOS.
        /// </summary>
        public static string SOS {
            get {
                return ResourceManager.GetString("SOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of opponents scores.
        /// </summary>
        public static string SOSD {
            get {
                return ResourceManager.GetString("SOSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOSOS.
        /// </summary>
        public static string SSS {
            get {
                return ResourceManager.GetString("SSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of opponents SOS.
        /// </summary>
        public static string SSSD {
            get {
                return ResourceManager.GetString("SSSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top group bar.
        /// </summary>
        public static string TopGroupBar {
            get {
                return ResourceManager.GetString("TopGroupBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament type.
        /// </summary>
        public static string TournamentType {
            get {
                return ResourceManager.GetString("TournamentType", resourceCulture);
            }
        }
    }
}
